### ISSUE TITLE
Parse `Transfer` events from token contract

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-electron#147]
In order to get the full tx history in the My Wallet page, we will need to parse transfer events from the BodhiToken contract.

**Comment by TT1943** [comment]
Any update on this issue?

**Comment by dwalintukan** [comment]
@xiahong This needs a big change on the BE. Might need to create another entire service just for parsing transfers. This will be post-mainnet launch.
@frankhu
