### ISSUE TITLE
Handle quitting while in the middle of parsing

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-electron#159]
@frankobe 
I think TT ran into an issue where he quit while a tx update was happening so it didn't complete. Then he was stuck with an Oracle that wasn't updated.

We need some way to handle if the user quits while in the middle of updates. What happens if in the middle of the sync the user quits?

**Comment by frankobe** [comment]
@dwalintukan no change should be made on models until parsing completes.  So even user quits app in the middle, the status is not updated so they will re-parse it again. 

if u r referring to a case where user quits app while db is updating. Then we need ensure all db writes are completed before kill the process

**Comment by dwalintukan** [comment]
Cool.  But ya we do need to handle when the db is in process of updating.

**Comment by frankobe** [comment]
@dwalintukan try holding the quite until finishing one block cycle

**Comment by dwalintukan** [comment]
makes sense. what about for force quits? edge case but still can happen.

**Comment by frankobe** [comment]
@dwalintukan we cant avoid it unless db support `transaction` so we can group a few operation in one transaction to determine whether to finish or revert all

**Comment by dwalintukan** [comment]
hmm right. ok guess we can discuss safety fallbacks later.

**Comment by frankobe** [comment]
1. ensure where is no mutation going on
2. set a flag to shut down the app, so all requests returns 404
3. shutdown app
